project:
  type: website

website:
  title: "magicdata-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme: vapor
    css: styles.css

editor: visual

